# Generated by Django 2.1.3 on 2018-12-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0003_auto_20181203_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubirTarea',
        ),
    ]
